Support of FILTER parameters with INTERSECTS
deegree/deegree-ogcapi pull request #118
Opened 2024-04-24 10:06 UTC by lgoltz

This PR implements parts of OGC API - Features - Part 3. The implementation is not fully supporting the following requirements classes: "Queryables", "Queryables as Query Parameters", "Filter" with "CQL2 Functions", and "Features Filter".
Implementation is limited to S_INTERSECTS({spatialQueryable},{spatialInstance})

2024-05-08 16:12 UTC, tfr42 commented on deegree-ogcapi-features/src/main/antlr4/org/deegree/services/oaf/cql2/Cql2.g4
Add source and license is missing

2024-05-08 16:15 UTC, tfr42 commented on deegree-ogcapi-features/src/main/antlr4/org/deegree/services/oaf/cql2/Cql2.g4
Taken from OGC sources,  https://portal.ogc.org/files/96288

2024-05-08 16:16 UTC, stephanr requested changes
The license header is missing for the new Java files in the package `org.deegree.services.oaf.cql2`.

Also, it is not clear to me if the added grammar file `cql2.g4` is also required to have a license header.

2024-07-17 15:55 UTC, dstenger approved these changes

2024-07-17 15:56 UTC, stephanr approved these changes

2024-07-17 15:56 UTC, merged