Update configVersion and schemaLocation in documentation to deegree version 3.5
deegree/deegree-ogcapi pull request #47
Opened 2022-08-16 16:08 UTC by julianzz98

Updated the configVersion of the example configurations in the documentation from 3.4.0 to 3.5.0.

The used schemaLocation needs a review, since as of now https://schemas.deegree.org/3.5/ does not list the schemas for OGC API.

2022-08-16 16:56 UTC, julianzz98 commented
Additionally, the URL should be adjusted that either http or https is used, not both.

2022-09-07 16:03 UTC, tfr42 requested changes
We need to verify the path to the schema files

2023-02-22 19:10 UTC, tfr42 commented
See also the related issue https://github.com/deegree/deegree-ogcapi/issues/19.

2023-05-24 16:19 UTC, tfr42 commented
@julianzz98 This PR is labled as duplicate. Which PR is replacing this one?

2023-05-24 16:27 UTC, julianzz98 commented
> @julianzz98 This PR is labled as duplicate. Which PR is replacing this one?

https://github.com/deegree/deegree-ogcapi/pull/98

2023-08-06 15:39 UTC, closed without merging